"""Load and dump Netscape cookie files for httpx."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import httpx


def load_netscape_cookies(path: Path) -> httpx.Cookies:
    """Parse a Netscape cookies.txt (as exported by 'Get cookies.txt LOCALLY' etc.)."""
    cookies = httpx.Cookies()
    if not path.is_file():
        return cookies
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        domain, _flag, cookie_path, _secure, _expires, name, value = parts[:7]
        cookies.set(
            name, value, domain=domain.lstrip(".") or domain, path=cookie_path or "/"
        )
    return cookies


def cookie_domains(cookies: httpx.Cookies) -> set[str]:
    return {c.domain for c in cookies.jar}


def apply_netscape_cookies(client: httpx.Client, path: Path) -> None:
    """Merge a Netscape cookies.txt into an httpx client."""
    if not path.is_file():
        return
    for c in load_netscape_cookies(path).jar:
        client.cookies.set(c.name, c.value, domain=c.domain, path=c.path)


def has_domain_cookies(client: httpx.Client, *fragments: str) -> bool:
    """True if the client jar has a cookie for any domain containing a fragment."""
    needles = [f.lower() for f in fragments]
    return any(
        any(n in (c.domain or "").lower() for n in needles) for c in client.cookies.jar
    )


def netscape_from_playwright(cookies: list[dict[str, Any]]) -> str:
    """Serialize Playwright `context.cookies()` dicts as a Netscape cookies.txt."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by paperful. Do not share or commit.",
        "",
    ]
    for c in cookies:
        name = str(c.get("name") or "")
        if not name:
            continue
        domain = str(c.get("domain") or "")
        path = str(c.get("path") or "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        raw_exp = c.get("expires")
        try:
            exp_i = int(raw_exp) if raw_exp is not None else 0
        except (TypeError, ValueError):
            exp_i = 0
        if exp_i < 0:
            exp_i = 0
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        prefix = "#HttpOnly_" if c.get("httpOnly") else ""
        value = str(c.get("value") or "")
        lines.append(
            f"{prefix}{domain}\t{flag}\t{path}\t{secure}\t{exp_i}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def write_netscape(path: Path, cookies: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(netscape_from_playwright(cookies), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def split_playwright_cookies(
    cookies: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Google-family cookies vs everything else (EZProxy / IdP / publishers)."""
    scholar: list[dict[str, Any]] = []
    other: list[dict[str, Any]] = []
    for c in cookies:
        domain = str(c.get("domain") or "").lower()
        if "google" in domain:
            scholar.append(c)
        else:
            other.append(c)
    return scholar, other
